#pragma once
// Generated by build script, do not edit!
#define UNITY_COMPANY "Unity Technologies"
#define UNITY_COPYRIGHT "(c) 2005-2023 Unity Technologies. All rights reserved."
#define UNITY_ENABLE_HWSTATS_REPORT 1
#define UNITY_BUILD_ROOT "C:/build/output/unity/unity"
